target: LeaveOrNot
features:
  - City
  - PaymentTier
  - Age
  - Gender
  - EverBenched
  - ExperienceInCurrentDomain
  - Education
  - JoiningYear
  
categorical_features:
 - 'City' 
 - 'Gender'
 - 'EverBenched'
 - 'Education'